# Generated by Django 6.0.2 on 2026-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatbottrainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Event', 'Event')], default='General', max_length=20),
        ),
    ]
