# Generated by Django 6.0.2 on 2026-04-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_driver_alter_user_role_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('attendance_date', models.DateField()),
                ('file', models.FileField(upload_to='attendance_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('records_imported', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
    ]
