# Generated by Django 6.0.2 on 2026-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accept_late_submissions',
            field=models.BooleanField(default=False),
        ),
    ]
