# Generated by Django 5.2.14 on 2026-05-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_assignment_semester_quiz_semester_resource_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_approval', models.BooleanField(default=True, help_text='If enabled, new signups require admin approval before they can log in. If disabled, users can log in immediately after signing up.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
