# Generated by Django 5.2.14 on 2026-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='semester',
            field=models.CharField(blank=True, default='General', max_length=20, null=True),
        ),
    ]
