"""
Django settings for digital_campus project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Detect Vercel environment (VERCEL env var is set to '1' by Vercel)
IS_VERCEL = bool(os.environ.get('VERCEL', ''))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env_file(file_path):
    """Minimal .env loader for local development."""
    if not file_path.exists():
        return
    for raw_line in file_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()
        if value and ((value[0] == value[-1]) and value[0] in ("'", '"')):
            value = value[1:-1]
        os.environ.setdefault(key, value)


# Load local env variables when running outside Vercel.
if not IS_VERCEL:
    _load_local_env_file(BASE_DIR / '.env.local')
    _load_local_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-%0mpkd4k^j^ixza_qi-xvu*7q)-5vrk2p@jtmicsw4^v_l^l&+')

# SECURITY WARNING: don't run with debug turned on in production!
# In production (Vercel), set DJANGO_DEBUG=False in environment variables
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allows local dev + any Vercel deployment domain automatically
if IS_VERCEL or not DEBUG:
    ALLOWED_HOSTS = ['*']  # Vercel handles host validation
else:
    ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Allow Vercel domains to submit forms (CSRF protection)
CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'https://*.now.sh',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digital_campus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digital_campus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# On Vercel, the filesystem is read-only except for /tmp
# We copy the SQLite DB to /tmp on startup for read/write access

import dj_database_url

if 'DATABASE_URL' in os.environ:
    # Use persistent PostgreSQL database
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif IS_VERCEL:
    import shutil
    # Use the actual bundled database name instead of assuming db.sqlite3
    db_name = os.environ.get('SQLITE_DB_NAME', 'db_local.sqlite3')
    DB_SOURCE = BASE_DIR / db_name
    DB_DEST = Path('/tmp/db.sqlite3')
    # Copy the bundled DB to /tmp on every cold start (Vercel project dir is read-only)
    if DB_SOURCE.exists():
        shutil.copy2(DB_SOURCE, DB_DEST)
    else:
        print(f"WARNING: Database {DB_SOURCE} not found! Vercel will start with an empty DB.")
        
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DB_DEST,
        }
    }
else:
    local_db_name = os.environ.get('SQLITE_DB_NAME', 'db.sqlite3')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / local_db_name,
            'OPTIONS': {
                'timeout': 20,  # 20 second timeout for database locks
                'init_command': "PRAGMA journal_mode=WAL;",  # Write-Ahead Logging for better concurrency
            }
        }
    }

# Sessions
if IS_VERCEL:
    # use signed cookies on Vercel (no disk writes needed, but keep chat history short)
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
else:
    # use default DB sessions locally for better performance with large payloads
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = IS_VERCEL  # HTTPS only on Vercel


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if not IS_VERCEL and DEBUG:
    # Use MD5 hasher for fast user creation and login in local dev only
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    ]
else:
    # Allow MD5 hasher as a fallback since local db.sqlite3 synced to Vercel contains MD5 hashed passwords
    # IMPORTANT: MD5 MUST be the FIRST hasher so Django does not auto-upgrade the password.
    # Auto-upgrading updates the DB, which gets lost on Vercel cold-starts, causing session hash mismatch logouts!
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2PasswordHasher',
        'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
        'django.contrib.auth.hashers.Argon2PasswordHasher',
        'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
        'django.contrib.auth.hashers.ScryptPasswordHasher',
    ]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

if IS_VERCEL or not DEBUG:
    # WhiteNoise for serving static files in production.
    # Use CompressedStaticFilesStorage so files are served correctly on Vercel.
    # NOT using CompressedManifest variant to avoid crashes if staticfiles.json is missing.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    # Fast native django static files for local development
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'
LOGIN_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# On Vercel the project dir is read-only; redirect media writes to /tmp
if IS_VERCEL:
    MEDIA_ROOT = '/tmp/media'

# Email Backend for Development (Console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- Gemini AI Chatbot ---
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')

