# Generated by Django 6.0.2 on 2026-02-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="The question referencing the topic (e.g., 'When is the exam?')")),
                ('answer', models.TextField(help_text='The answer the bot should give.')),
                ('keywords', models.CharField(help_text="Comma-separated keywords for matching (e.g., 'exam, date, schedule')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
