# Generated by Django 6.0.2 on 2026-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solution Provided', 'Solution Provided'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
