# Generated by Django 6.0.2 on 2026-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quiz_question_quizresult_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
