# Generated by Django 5.2.14 on 2026-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='1st Semester', max_length=50),
        ),
    ]
